FROM timeseries-train

# Install dependencies
# RUN pip3 install pandas

# Directory for src code
# RUN mkdir /workdir

# Copy source code to docker image
COPY src/preprocess_data.py /workdir

# Change working directory to app
WORKDIR /workdir
