apiVersion: v1
kind: Service
metadata:
  labels:
    app: fintech
  name: fintech-service
  namespace: kubeflow
spec:
  ports:
  - name: grpc-tf-serving
    port: 9000
    targetPort: 9000
  - name: http-tf-serving
    port: 8500
    targetPort: 8500
  selector:
    app: fintech
  type: ClusterIP
